# 1. Import numpy and print version

In [1]:
import numpy as np
print(np.__version__)

2.0.2


## 2. Create 1d array

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## 3. Create 3x3 boolean array



In [3]:
bool_array = np.full((3, 3), True, dtype=bool)
print(bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 4. Extract odd numbers

In [4]:
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


## 5. Replace odd numbers in arr


In [5]:
arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 6. Replace odd numbers without changing arr


In [6]:
arr_copy = arr.copy()
arr_copy[arr_copy % 2 != 0] = -1
print("New array with odd numbers replaced:")
print(arr_copy)
print("Original array:")
print(arr)

New array with odd numbers replaced:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original array:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 7. Convert 1d to 2d array


In [7]:
arr_1d = np.arange(10)
arr_2d = arr_1d.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 8. Stack arrays vertically


In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stacked_array = np.vstack((a, b))
print(stacked_array)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 9. Stack arrays horizontally


In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
horizontal_stacked_array = np.hstack((a, b))
print(horizontal_stacked_array)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## 10. Create pattern

In [20]:
a = np.array([1,2,3])
pattern = np.tile(np.repeat(a, 3), 2)
print(pattern)

[1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3]


## 11. Get common items

In [21]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


## 12. Remove items

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
items_to_remove = np.isin(a, b)
new_a = a[~items_to_remove]
print(new_a)

[1 2 3 4]


## 13. Get matching positions

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matching_positions = np.where(a == b)
print(matching_positions)

(array([1, 3, 5, 7]),)


## 14. Get all items between 5 and 10 from a

In [25]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
items_between_5_and_10 = a[(a >= 5) & (a <= 10)]
print(items_between_5_and_10)

[ 6  9 10]


## 15. Swap columns 1 and 2 in the array arr

In [26]:
arr = np.arange(9).reshape(3,3)
arr[:, [1, 2]] = arr[:, [2, 1]]
print(arr)

[[0 2 1]
 [3 5 4]
 [6 8 7]]


## 16. Swap rows 1 and 2 in the array arr

In [27]:
arr = np.arange(9).reshape(3,3)
arr[[1, 2], :] = arr[[2, 1], :]
print(arr)

[[0 1 2]
 [6 7 8]
 [3 4 5]]


## 17. Reverse the rows of a 2D array arr

In [28]:
arr = np.arange(9).reshape(3,3)
reversed_arr = arr[::-1, :]
print(reversed_arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


## 18. Reverse the columns of a 2D array arr

In [29]:
arr = np.arange(9).reshape(3,3)
reversed_cols_arr = arr[:, ::-1]
print(reversed_cols_arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## 19. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [30]:
rand_arr = 5 + (np.random.random((5, 3)) * 5)
print(rand_arr)

[[8.23976424 9.60572958 6.85819553]
 [5.72976436 7.83246208 6.07808441]
 [7.21299209 9.95413878 7.13786841]
 [5.27212243 5.15725835 5.63527756]
 [6.33486956 9.99566544 5.49635711]]


## 20. Print or show only 3 decimal places of the numpy array rand_arr.

In [32]:
np.set_printoptions(precision=3)
print(rand_arr)

[[8.24  9.606 6.858]
 [5.73  7.832 6.078]
 [7.213 9.954 7.138]
 [5.272 5.157 5.635]
 [6.335 9.996 5.496]]


## 21. Pretty print rand_arr by suppressing the scientific notation

In [35]:
np.set_printoptions(suppress=True)
print(rand_arr)

[[8.24  9.606 6.858]
 [5.73  7.832 6.078]
 [7.213 9.954 7.138]
 [5.272 5.157 5.635]
 [6.335 9.996 5.496]]


## 22. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [36]:
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


## 23. Print the full numpy array a without truncating.

In [37]:
np.set_printoptions(threshold=np.inf)
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 24. Import the iris dataset keeping the text intact.

In [38]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:5]) # Display the first 5 rows to verify

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


## 25. Extract the text column species from the 1D iris imported in previous question.

In [39]:
species = iris[:, 4]
print(species[:5]) # Display the first 5 elements to verify

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


## 26. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [40]:
iris_2d = iris[:, :4].astype('float')
print(iris_2d[:5]) # Display the first 5 rows to verify

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## 27. Find the mean, median, standard deviation of iris's sepallength (1st column).

In [41]:
sepallength = iris_2d[:, 0] # Extract the first column (sepallength)

mean_sepallength = np.mean(sepallength)
median_sepallength = np.median(sepallength)
std_sepallength = np.std(sepallength)

print(f"Mean of sepallength: {mean_sepallength:.2f}")
print(f"Median of sepallength: {median_sepallength:.2f}")
print(f"Standard deviation of sepallength: {std_sepallength:.2f}")

Mean of sepallength: 5.84
Median of sepallength: 5.80
Standard deviation of sepallength: 0.83


## 28. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [42]:
# Min-Max Normalization
min_val = np.min(sepallength)
max_val = np.max(sepallength)
normalized_sepallength = (sepallength - min_val) / (max_val - min_val)

print("Normalized sepallength (first 10 values):")
print(normalized_sepallength[:10])

Normalized sepallength (first 10 values):
[0.222 0.167 0.111 0.083 0.194 0.306 0.083 0.194 0.028 0.167]


## 29. Find the 5th and 95th percentile of iris's sepallength.

In [43]:
percentile_5 = np.percentile(sepallength, 5)
percentile_95 = np.percentile(sepallength, 95)

print(f"5th percentile of sepallength: {percentile_5:.2f}")
print(f"95th percentile of sepallength: {percentile_95:.2f}")

5th percentile of sepallength: 4.60
95th percentile of sepallength: 7.25


## 30. Insert np.nan values at 20 random positions in iris_2d dataset

In [44]:
iris_nan = iris_2d.copy()

# Get the total number of elements in the array
total_elements = iris_nan.size

# Generate 20 random indices
random_indices = np.random.choice(total_elements, 20, replace=False)

# Convert the flat indices to 2D indices
row_indices, col_indices = np.unravel_index(random_indices, iris_nan.shape)

# Insert np.nan at the random positions
iris_nan[row_indices, col_indices] = np.nan

print("Iris dataset with 20 random NaN values (first 10 rows):")
print(iris_nan[:10])

Iris dataset with 20 random NaN values (first 10 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [nan 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


## 31. Find the number and position of missing values in iris_2d's sepallength.

In [45]:
sepallength_with_nan = iris_nan[:, 0] # Extract the sepallength column which might have NaNs

missing_values_mask = np.isnan(sepallength_with_nan)
number_of_missing = np.sum(missing_values_mask)
positions_of_missing = np.where(missing_values_mask)

print(f"Number of missing values in sepallength: {number_of_missing}")
print(f"Positions of missing values in sepallength: {positions_of_missing}")

Number of missing values in sepallength: 4
Positions of missing values in sepallength: (array([  2,  33, 110, 141]),)


## 32. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.

In [46]:
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print("Filtered rows:")
print(filtered_rows)

Filtered rows:
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## 33. Select the rows of iris_2d that does not have any nan value.

In [47]:
# Select rows that do not contain any NaN values
rows_without_nan = iris_nan[~np.isnan(iris_nan).any(axis=1)]

print("Rows without NaN values (first 10 rows):")
print(rows_without_nan[:10])

Rows without NaN values (first 10 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]]


## 34. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d.

In [48]:
# Assuming iris_2d is available from previous steps
sepallength = iris_2d[:, 0] # 1st column
petallength = iris_2d[:, 2] # 3rd column

correlation = np.corrcoef(sepallength, petallength)[0, 1]

print(f"Correlation between SepalLength and PetalLength: {correlation:.2f}")

Correlation between SepalLength and PetalLength: 0.87


## 35. Find out if iris_2d has any missing values.

In [49]:
has_missing = np.isnan(iris_nan).any()

if has_missing:
    print("The iris_nan array has missing values.")
else:
    print("The iris_nan array does not have any missing values.")

The iris_nan array has missing values.


## 36. Replace all occurrences of nan with 0 in numpy array.

In [50]:
# Create a copy to avoid modifying the original iris_nan array
iris_filled = np.nan_to_num(iris_nan, nan=0)

print("Iris dataset with NaN values replaced by 0 (first 10 rows):")
print(iris_filled[:10])

Iris dataset with NaN values replaced by 0 (first 10 rows):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [0.  3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


## 37. Find the unique values and the count of unique values in iris's species

In [51]:
unique_species, counts = np.unique(species, return_counts=True)

print("Unique species:", unique_species)
print("Count of unique species:", counts)

Unique species: [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
Count of unique species: [50 50 50]
